export const CATEGORIAS = [
  'PUBLICO',
  'SAUDE',
  'EDUCACAO',
  'LAZER',
  'TRANSPORTE',
  'ALIMENTACAO',
  'HOSPEDAGEM',
  'SERVICOS',
  'COMERCIAL',
];

export const TIPO_ACESSIBILIDADE = [
  'RAMPA_DE_ACESSO',
  'BANHEIRO_ADAPTADO',
  'ELEVADOR_ACESSIVEL',
  'PISO_TATIL',
  'SINALIZACAO_EM_BRAILLE',
  'ESTACIONAMENTO_ACESSIVEL',
  'ESPACO_AMPLO',
  'RECURSOS_AUDIOVISUAIS',
  'ATENDIMENTO_ESPECIALIZADO',
  'MOBILIARIO_ADAPTADO',
];