export const CATEGORIAS = [
  'COMERCIAL',
  'PUBLICO',
  'SAUDE',
  'EDUCACAO',
  'LAZER',
  'TRANSPORTE',
  'ALIMENTACAO',
  'HOSPEDAGEM',
  'SERVICOS',
];

export const TIPO_ACESSIBILIDADE = [
  'RAMPA',
  'ELEVADOR',
  'BANHEIRO_ADAPTADO',
  'PISO_TATIL',
  'SINALIZACAO_BRAILLE',
  'ESTACIONAMENTO',
  'ESPACO_AMPLO',
  'RECURSOS_AUDIOVISUAIS',
  'ATENDIMENTO_ESPECIALIZADO',
  'MOBILIARIO_ADAPTADO',
];