logging.level.com.acessolivre=DEBUG
logging.level.com.acessolivre.security=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.cache=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Email - Mailhog para desenvolvimento local
spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=*

# Email from address
spring.mail.properties.mail.from=noreply@acessolivre.com.br
